name: simple_throttle_debounce_example
description: "It's a simple pure dart package which implements throttle/debounce functionality, and it's a rewrite work of the original js version (JavaScript patterns: Throttle and Debounce)"
version: 1.0.1
repository: https://github.com/liudonghua123/simple_throttle_debounce

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  simple_throttle_debounce:
    path: ..

dev_dependencies:
  pedantic: ^1.11.1
  test: ^1.21.6
