name: simple_throttle_debounce
description: "It's a simple pure dart package which implements throttle/debounce functionality, and it's a rewrite work of the original js version (JavaScript patterns: Throttle and Debounce)"
version: 1.0.0
repository: https://github.com/liudonghua123/simple_throttle_debounce

environment:
  sdk: ">=2.9.0 <3.0.0"

#dependencies:
#  path: ^1.7.0

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
