name: Pipeline

on:
  push:
    branches:
      - master
    tags:
      - "*"

jobs:
  publish_simple_throttle_debounce:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: ">> publish simple_throttle_debounce <<"
        id: publish
        uses: liudonghua123/dart-package-publisher@dev
        with:
          credentialJson: ${{ secrets.CREDENTIAL_JSON }}
          relativePath: .
          skipTests: true