name: Pipeline

on:
  push:
    branches:
      - master

jobs:
  publish_simple_throttle_debounce:
    env:
      CREDENTIAL_JSON: ${{ secrets.CREDENTIAL_JSON }}
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - name: Branch name
        id: branch_name
        run: |
          echo ::set-output name=SOURCE_NAME::${GITHUB_REF#refs/*/}
          echo ::set-output name=SOURCE_BRANCH::${GITHUB_REF#refs/heads/}
          echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}

      - uses: actions/setup-java@v1
        with:
          java-version: "8.x"
      - uses: subosito/flutter-action@v1
        with:
          channel: "dev"

      - name: Enable web/desktop support
        run: |
          flutter config --enable-web
          flutter config --enable-macos-desktop
          flutter config --enable-linux-desktop
          flutter config --enable-windows-desktop

      - name: Copy credentials
        run: |
          mkdir -p ~/.pub-cache
          echo $CREDENTIAL_JSON > ~/.pub-cache/credentials.json
          cat ~/.pub-cache/credentials.json

      - name: ">> publish simple_throttle_debounce <<"
        id: publish
        run: |
          pub get
          pub publish -n
          pub --trace publish -f
